#!/usr/bin/env bash
# creating script to tranfer file to remote server

if [ $# -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign arguments to variables
LOCAL_FILE="$1"
REMOTE_IP="$2"
REMOTE_USER="$3"
SSH_KEY="$4"

# Perform the file transfer using SCP
scp -i "$SSH_KEY" "$LOCAL_FILE" "$REMOTE_USER@$REMOTE_IP:~/"
