#!/usr/bin/env bash
# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Ensure Nginx is configured to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/g' /etc/nginx/sites-available/default

# Allow 'Nginx HTTP' through the firewall to listen on port 80
sudo ufw allow 'Nginx HTTP'

# Create an HTML file containing "Hello World!" in the default web directory
#alternative look bellow this line: for echo "hello world" | sudo tee /var/www/html/index.html 
#sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo bash -c 'cat > /etc/nginx/sites-available/default' <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri /index.html;
    }
}
EOF
# Reload Nginx to apply the new configuration
sudo nginx -s reload
