#!/usr/bin/env bash                                                                                                                                                    
#Install nginx web server                                                                                                                                              
sudo apt-get -y update                                                                                                                                                 
sudo apt-get -y install nginx                                                                                                                                          
                                                                                                                                                                       
# Define the Nginx configuration file path                                                                                                                             
NGINX_CONF="/etc/nginx/sites-available/default"                                                                                                                        
                                                                                                                                                                       
# Add the redirect configuration                                                                                                                                       
sudo sed -i '/server_name _;/a \\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=nTKEx3OoxNs;\n    }\n' /etc/nginx/sites-available/def
ault                                                                                                                                                                   
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'                                                                                               
sudo service nginx start                                                    
