#!/usr/bin/env bash
# Find the PID of the process with name "4-to_infinity_and_beyond"
_pid=$(pgrep -f '4-to_infinity_and_beyond')

# Check if the PID is not empty
if [ -n "$_pid" ]; then
    # Kill the process with SIGKILL (9)
    kill -9 "$_pid"
else
    echo "Process not found."
fi

