#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

name="Best School"
word="Hi"
i=0

while [ $i -lt 10 ]
do 
  if [ $i != 8 ]; then
     echo "$name"
  else
  	echo $word
  fi
  ((i++))
done


