#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and:
# - displays "bad luck" for the 4th loop iteration
# - displays "good luck" for the 8th loop iteration
# - displays "Best School" for the other iterations

name="Best School"
word1="bad luck"
word2="good luck"

i=1
four=4
eight=8


while [ $i -le 10 ]
do 
  if [ $i == $four ]
  then
  	echo "$word1"
  elif [ $i == $eight ]
  then
  	echo "$word2"
  else
  	echo "$name"
  fi
  ((i++))
done
