#!/usr/bin/env bash
# Write a Bash script that gives you information about the school file.

file_name="./school"

if [ -e "$file_name" ]; then
   echo "File exists" 
   if [ -s "$file_name" ]; then
      echo "File is not empty"
   else
      echo "File is empty"
   fi
   if [ -f "$file_name" ]; then
      echo "school is a regular file"
    else
      echo "school is not a regular file"
    fi
else 
   echo "school file does not exist"
fi